### ISSUE TITLE
Can we have the option of changing the order of timers vertically?

### ISSUE THREAD

**Issue by amhoba2014** [timer-machine/timer-machine-android#109]
I mean currently the order of timers can not be changed. Lets say I have 5 timers in the default set and I want to reorder them to making them look clean and neat. Its not possible at the moment. Only I have the option of duplicating them and then remove the old one, which just moves the duplicated one to the end which limits the movement of timers and is like a puzzle to solve!

Please add this feature. Thanks! I'm a fan!

**Comment by DeweyReed** [comment]
At the top right corner of the timer list, there is a reordering button on the left of the more button(three dots). The function is limited, but it at least allows reordering.
