### ISSUE TITLE
Show time remaining for full exercise

### ISSUE THREAD

**Issue by Donkey-Doug** [timer-machine/timer-machine-android#11]
Please add an option to show the total time remainingm

**Comment by DeweyReed** [comment]
1. Open the app.
2. Tap the menu button(three horizontal lines) at the top-left corner.
3. Tap "Settings."
4. Tap "Customize Screen."
5. Tap the gear icon at the bottom of the screen.
6. Tap "Time Panel Picker."
7. Select "Remaining time."
8. Tap "OK."
9. The remaining time of the whole exercise should appear above the time text on the running screen.

Let me know if this solves your problem. :D

**Comment by Donkey-Doug** [comment]
Ah yes, in the top left corner the time is shown. Maybe make it possible to change the large main timer?

**Comment by DeweyReed** [comment]
By "the large main timer," do you mean the text size of the current remaining time? If so, you can change it in the abovementioned 6th step. There is a slide bar above "Time Panel Picker," and you can slide it to change the text size.
