### ISSUE TITLE
希望用户能对统计页里默认展示的计时器分组和时间范围做出调整

### ISSUE THREAD

**Issue by j-wyatt-a** [timer-machine/timer-machine-android#12]
你好，您的软件对我的帮助非常大，而且我非常佩服您的设计品位

我目前在使用中有这样的问题：
我有八个计时器，我对他们分成了 ABC 三组，当我想看 A 组的统计信息的时候，进入统计页里，每次都需要手动取消其他分组的打钩
我还经常看今天这个时间段里的计时器使用记录，也是每次都要手动的选择

就是这样每次进入统计页都要选择一遍让我感觉有些费力，我想能不能给出两个可以设置的默认选项，这样能减少这样的手动操作

如果您能提供这样的选项，我会非常感谢。我尝试过自己对软件做出修改，但我实在对 Android 不太熟悉，所以如果您能指出在这个功能的实现需要在哪里做出修改，也同样谢谢您。

**Comment by DeweyReed** [comment]
现在应用会缓存统计页面的标签。那如果缓存所选计时器和时间的话，应该就可以解决这个问题。有什么潜在的风险吗？我暂时还想不到。

**Comment by j-wyatt-a** [comment]
这个标签指的就是「概况、时间线、日历」这三个吧，我现在能看到它们的缓存效果。如果把时间和分组的选择也带有这样的缓存效果那确实挺好的。

**Comment by DeweyReed** [comment]
https://github.com/timer-machine/timer-machine-android/commit/79489cd2816fd356665cd9ff64ec38dc86c84085

**Comment by j-wyatt-a** [comment]
非常好的修改，希望能更新一下安装包，非常感谢

**Comment by j-wyatt-a** [comment]
非常好用
