### ISSUE TITLE
Image for exercice

### ISSUE THREAD

**Issue by Morglaf** [timer-machine/timer-machine-android#30]
A image or gif or movie can be useful for some exercice.

Thx

**Comment by DeweyReed** [comment]
This feature is both lovely and complicated.

**Comment by Minabsapi** [comment]
I happened to need that too, so I just hacked that feature in. PR incoming

**Comment by 2018robert** [comment]
I also need this. Physiotherapists are always handing out sheets of paper with instructions and images. It would be great to have them here.

**Comment by DeweyReed** [comment]
I've been working on the feature in another branch for some time. It will take more time due to my lack of time and the complexity of the feature.

There is a pull request that implements the feature, but it probably won't be compatible with the current branch.

**Comment by DeweyReed** [comment]
The image reminder was added in #92. However, backup files don't include images. I'll open a new issue for the matter.

**Comment by Profi20081** [comment]
Hi, are there plans to add GIFs alongside images soon?

**Comment by DeweyReed** [comment]
@Profi20081 The image reminder already supports GIFs. The aspect ratio seems broken when I test it today. I'll fix it in the next release.

**Comment by Profi20081** [comment]
@DeweyReed Ah, okay, but in the window that opens to select the image or GIFs, I can only choose from my own images. The GIFs don't show up.
I am on android 16.

**Comment by DeweyReed** [comment]
@Profi20081 Can you find those GIFs in the system gallery app, like Files or Google Photos? If the GIFs are from the computer, they may stay hidden from apps until you manually move them into a directory like Pictures.
