### ISSUE TITLE
Show total duration in list

### ISSUE THREAD

**Issue by dcdom2** [timer-machine/timer-machine-android#36]
When in timer list (inside a set), it would be useful to show total duration of each timer.

**Comment by DeweyReed** [comment]
Insufficient screen space.

You could include a rough duration of the timer in the timer's name.

**Comment by dcdom2** [comment]
I think that the [current item size could both be smaller and still allow for more info](#39). It can be in tiny font. Also see TimerDroid.

**Comment by DeweyReed** [comment]
After applying some material guidelines, like the smallest icon size and font size, minimum space, etc., the app's screen has been quite crowded.

Since I'm not good at UI designing, I have difficulty putting more into the card. 👯

**Comment by dcdom2** [comment]
Personally, I think Material U wastes too much space. I hope that you reconsider when the opportunity arises.

**Comment by DeweyReed** [comment]
I'm not a UI designer and not good at designing at all. Material is the only guideline that's easier for me without a designer. Until finding some sound design for the project, mindlessly renovating UI is not a good idea.

**Comment by dcdom2** [comment]
I understand. I hope you can consider it when the time comes to work on the design.
