### ISSUE TITLE
"Show all" view

### ISSUE THREAD

**Issue by dcdom2** [timer-machine/timer-machine-android#38]
In the set drop-down list, provide "All" which shows all the timers in different sets.

**Comment by DeweyReed** [comment]
This feature isn't very helpful, just like listing all files under all folders in the file explorer. Organize timers into a folder if they serve a similar purpose.

**Comment by dcdom2** [comment]
I think it is very useful to start (and follow) timers from different sets at the same time.

Just to clarify, I am talking about real-world use cases in my work. Also think of starting cooking and gardening. Or cooking and reading. etc.

**Comment by DeweyReed** [comment]
Wouldn't it be nice to put all timers into one set and call the set daily routine or something?

I think organizing by usage instead of type can be helpful, especially when the number of items is large, just like how we manage our code.
