### ISSUE TITLE
Consistent Time Panel item order

### ISSUE THREAD

**Issue by dcdom2** [timer-machine/timer-machine-android#40]
In time panel, always show "step end time" to the left of "timer end time".

Better yet, show "timer end time" on the upper right corner.

**Comment by DeweyReed** [comment]
Time panels show in the same order that you configure them. So select "step end time" first to make it appear in the first place.

There are many time panels, so it's unfair to designate one to a specific position.

**Comment by dcdom2** [comment]
I see. No problem.
