### ISSUE TITLE
New app idea: SOP

### ISSUE THREAD

**Issue by dcdom2** [timer-machine/timer-machine-android#41]
TimeR Machine makes routines easier and more manageable, including in professional settings . It would be awesome if you also make an app for standard operating procedures: checklists where you can create a new one for a specific date and time and tick off the applicable items.

Thanks

**Comment by DeweyReed** [comment]
Thank you for using the app and sharing your advice!

There have been a lot of excellent to-do-list apps on the market. You may want to try some already successful ones.

**Comment by dcdom2** [comment]
I didn't mean a regular to-do list app but something like a take-off checklist. Something reusable.

Imagine that you are an inspector and have a fixed list of items you review for each location/day/etc.

**Comment by DeweyReed** [comment]
I have a fixed list of missions I must do every day. And I use a to-do list app and postpone every task until the next day after finishing it. Those apps are very mature and provide advanced features I can't implement, like syncing across multiple platforms.

**Comment by dcdom2** [comment]
No problem. Thanks for the great software you do develop.

**Comment by DeweyReed** [comment]
Hi, I want to share an app I just found with you. [Todoist](https://todoist.com/) can create recurring tasks that reschedule themselves after completion. There are some free quotas for a free account.

**Comment by dcdom2** [comment]
What I had in mind was something like this

<img src="https://play-lh.googleusercontent.com/2Bbwk4pnTW30HwyQA1B5nmxdOgLyn7dp0oJboEOR7FAJwVKSiVeS_xZdjRKmc2emiZE=w2560-h1440" height="400" /> or this <img src="https://play-lh.googleusercontent.com/ojkX-nFBRgGvB3lfx0tCc5mz_nvwnrVizSCQx6kc6mmwJFQFT-kni7nZwJO5UMK11a28=w2560-h1440" height="400" />

A template that you can as many times as you wish and records the previous entries (by date or location etc). Like an inspector inspecting apartments or pre-flight checklist.

The closest apps I can find to approximate what I mean is [Loop Habit Tracker](https://github.com/iSoron/uhabits) (the idea of following individual daily tasks over time) or 

<img src="https://github.com/iSoron/uhabits/blob/dev/screenshots/4.png?raw=true" height="400" />

or [Reusable Checklist](https://play.google.com/store/apps/details?id=cz.kudlav.reusablechecklist) (the idea of templates that can be used at will and repeatedly).

<img src="https://play-lh.googleusercontent.com/SBvqIo2iaM544FdqMxPJOhScgU2Rb9XCJYkWP2oAjaUWktUYvvxU_Rt6rT8U3jorUk8=w2560-h1440" height="400" />

**Comment by dcdom2** [comment]
Think of it as someone going to work and has a fixed list of todos/check-ups/inspections to do every shift. And to be able to see their history (how many days in the last month did I do X? when was the last time I found Y malfunctioning? etc)

**Comment by DeweyReed** [comment]
That's very professional. There may be similar apps in some professional industries. Or you can consider building one. It's exciting and proud to create apps and share them with others. :D

**Comment by dcdom2** [comment]
I can't code, unfortunately.

**Comment by DeweyReed** [comment]
Okay. Learning to build Android apps has been a lot easier these days. BTW, The best thing about maintaining an app by oneself is that you can always tailor it. :D
