### ISSUE TITLE
Per-timer toggle for no notifcation

### ISSUE THREAD

**Issue by dcdom2** [timer-machine/timer-machine-android#42]
For ***some*** timers, I don't need a notification. Can there by an option in the timer settings to run without popping up notifications?

Currently the only solution is to disable app notifications altogether.

**Comment by DeweyReed** [comment]
The timer editing screen has a gear icon on the left of the timer name. Tap it, and turn off the first option in the pop-up. All timers with this setting will merge into one notification. Unfortunately, there must be at least one notification. Otherwise, it's easier to get killed by the system.

**Comment by dcdom2** [comment]
Ah, I see! I have missed it. Thanks!
