### ISSUE TITLE
Double tap work (in step title) to select

### ISSUE THREAD

**Issue by dcdom2** [timer-machine/timer-machine-android#47]
When in step or notifier title, double tapping should highlight the current word.

**Comment by DeweyReed** [comment]
You can double tap the step number to jump to it.

![Example](https://github.com/timer-machine/Grocery/raw/master/images/double-tap-to-jump.webp)

**Comment by dcdom2** [comment]
Thanks, but I meant in the edit screen.

**Comment by dcdom2** [comment]
> By "highlight," do you mean select all text? Do you wish to select all text by double tapping?

Just the current word. It is a standard Android behavior.

https://docs.flutter.dev/assets/images/docs/platform-adaptations/text-double-tap-android.gif

**Comment by DeweyReed** [comment]
That is the app's current behavior. I've verified it on several physical devices. How different does your app behave?

**Comment by dcdom2** [comment]
It is working for me now. I don't know why!

Sorry and thanks!
