### ISSUE TITLE
Timer does not trigger when screen is off on S23

### ISSUE THREAD

**Issue by darorl89** [timer-machine/timer-machine-android#49]
Timer does not trigger when screen is off on S23. It worded well on S8 but for some reason, I guess system sleep mode management issue prevents the timer to start up until the screen is turned on again (I have the app on never put to sleep). Any way to circumvent that?

**Comment by DeweyReed** [comment]
There are a lot of settings you can configure.
[dontkillmyapp.com/samsung](https://dontkillmyapp.com/samsung)
The app also has a Whitelist Guideline on the help page.

**Comment by darorl89** [comment]
That did the job, thank you.
