### ISSUE TITLE
Display goes to sleep while timer is used

### ISSUE THREAD

**Issue by NiceWeather** [timer-machine/timer-machine-android#53]
When I start a timer and wait 30 seconds, the display goes to sleep.  The app has the permission to disable the sleep mode.  The disabling of the sleep mode works with another app (tabata timer), so I think that this is a problem with this app (timer machine).

My device: Motorola g30, android 12 and samsung galaxy a41, android 12.

**Comment by DeweyReed** [comment]
If I remember correctly, you need to stay in the app after enabling the setting to prevent the screen from going off.

**Comment by NiceWeather** [comment]
I stay in the app (of course).  I'm using a two minute timer and I want to see the remaining time during the complete two minutes without interacting with the screen.

**Comment by DeweyReed** [comment]
In the app settings, what's the value of the option "Screen Brightness?" By default, the app doesn't keep the screen on.

**Comment by NiceWeather** [comment]
The value was "Dim the screen".  I changed it to "Keep the screen on".  It works.  Thanks, I close the issue.
