### ISSUE TITLE
Start Timer duplication leads to problems 

### ISSUE THREAD

**Issue by drlight-code** [timer-machine/timer-machine-android#57]
Hi and kudos for writing this software! <3

The start timer can be duplicated which leads to inconsistent behavior. 

Example way to reproduce:
- add start timer
- duplicate the start timer
- add a regular timer after the first start timer

This will leave you with two "start" timers that can not be moved by themselves, yet there is a normal timer in between them.

**Comment by drlight-code** [comment]
Oh i'm using version 7.3.0 from current F-Droid

**Comment by DeweyReed** [comment]
Thanks for your feedback! I'll fix the problem in the next release.
