### ISSUE TITLE
Database Synchronization

### ISSUE THREAD

**Issue by robsoncruzs** [timer-machine/timer-machine-android#65]
There could be an option to configure the database for recording, this would make it possible to synchronize the file (such as through Syncthing) and then have a backup option. If the backup & Respore option for export could be automatic (programmable) it would be enough.

**Comment by DeweyReed** [comment]
A backup feature is available as a premium feature in the Google Play channel. If you build and modify the app as needed, you can also use a custom Firebase project to store your data.
