### ISSUE TITLE
新功能请求

### ISSUE THREAD

**Issue by mobilisms** [timer-machine/timer-machine-android#69]
你好，不知有没有考虑添加一个“冻结”的功能，类似现在计时器执行过程中的“移动到下一步”，只不过冻结就好比自动跳过。可以出现在执行过程中又或者编辑过程中，都是比较方便的。

比如在一组循环中，某个步骤这次不需要又不想删除，就把它冻结了，然后跳过该步骤，继续执行接下来的步骤。

**Comment by DeweyReed** [comment]
你好！冻结也需要手动开启吧，这样的话和手动点击下一步的操作所需的操作步骤几乎一样。
如果需要总是跳过某一步骤，除了将该步骤删除外，还可以在计时器运行界面的步骤列表中，长按步骤时间，将时间设置为1秒。这样可以快速编辑计时器的时间。

**Comment by mobilisms** [comment]
一年前用软件记录并安排运动康复运动时间，很长一段时间每天早晚健康状态反复无常，大体是往好的方向发展。

所以刚开始时，频繁修改运动步骤时间与休息步骤的时间，时间长了就会忘记之前的参数。这样无法记录运动是否进步，少了成就感与激励。不得已就创建多个相同的计时器，区别就在运动时间休息时间不同。

直到现在有时感觉状态倍棒，就会选择少休息时间。感觉不妙，秒怂。昨晚感觉要是有个冻结功能，那就是只用一个计时器，就可以记录并体现出历史记录，看着递增的运动时间和逐渐减少的休息时间，能对于我这种长期康复运动人员是能够带来更多的激励和信心的。

所以才有了这么一个冻结功能请求，但无论如何非常感谢这么棒的应用。

**Comment by DeweyReed** [comment]
很高兴应用能帮到你！

这里需要冻结的步骤是不好预测的，所以总是需要二次编辑计时器。

我能想到一些可能更方便的替代方案。除了长按步骤时间快速修改时间，还可以创建多个休息的步骤。每次休息时，通过双击快速选择一个步骤运行。
![双击快速选择一个步骤](https://github.com/timer-machine/Grocery/raw/master/images/double-tap-to-jump.webp)
在打开应用设置中的时间微调选项后，还可以更精确地修改步骤剩余时间。

历史记录中可以选择并显示多个计时器的记录哦。

**Comment by mobilisms** [comment]
非常感谢，应用对个人来说真是个效率与规律神器。
 
应用功能也是越来越丰富，特别是历史记录，非常给力。就是单独查看单个计时器记录，操作步骤有点多，如果在计时器界面点击直达会不会好点，特别是放在计时器界面编辑里可供选择，对于是否启用，用户也有了自行选择的机会。

**Comment by DeweyReed** [comment]
在运行界面或编辑页面跳转历史记录，需要完全重写这两个页面，这并不是一个明智的做法。我想想有什么更好的办法。
