### ISSUE TITLE
Please make APK available outside PlayStore

### ISSUE THREAD

**Issue by IzzySoft** [timer-machine/timer-machine-android#7]
Could you please make the APK (ideally of the google-free `other` build flavor) available here in the repo – e.g. by [tagging releases](https://github.com/timer-machine/timer-machine-android/releases) and attaching the corresponding APK file? Some folks cannot (or do not want to) use PlayStore (e.g. for privacy reasons). Thanks in advance!

**Comment by DeweyReed** [comment]
I'll put APKs of the next version on the release page. Since there is still some code work, the next version will take several weeks. For now, anyone can download the APK of the `google` flavor by [this link](https://github.com/timer-machine/Grocery/blob/master/en/qa.md#google-play-apk).

**Comment by IzzySoft** [comment]
Thanks! I'll then wait until the tags are ready here. Would be great when at that point you could drop a note in this issue again :heart_eyes:

**Comment by DeweyReed** [comment]
I published [a pre-release version in the release tab](https://github.com/timer-machine/timer-machine-android/releases/tag/7.0.0). The version is also in the open testing channel in Google Play.

It will go to the stable in one or two weeks if everything goes right.

**Comment by IzzySoft** [comment]
Thanks a lot! Will [show up here](https://apt.izzysoft.de/fdroid/index/apk/io.github.deweyreed.timer.other) then with the next sync around 6 pm UTC (i.e. in less than 8 hours from now). I've picked screenshots and icon from PlayStore, hope that's fine with you. If you wish to proceed to [F-Droid.org](https://f-droid.org/) itself I happily provide you with the resulting metadata in Fastlane format for that, just let me know then.

Before you ask: my repo fetches updates within 24h of your tagging a new release and adding the APK to it. And you're of course welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to place next to the PlayStore one, linking to your app in my repo :smiley:

**Comment by DeweyReed** [comment]
@IzzySoft  Thank you! It's totally fine to me.

I want to practice submitting to F-Droid by myself. If I had any problem, I would surely ask you. :D

**Comment by IzzySoft** [comment]
@DeweyReed now that your app reached F-Droid (and with reproducible builds at that, congrats!) I'd usually remove it from my repo – unless the author explicitly requested to keep it. Now I see your Readme still carries my badge, which seems to be an "implicit request" :stuck_out_tongue_winking_eye: I guess that means you want me to keep it in? As it's decently sized and even has reproducible builds, I'd see no issues with that (apart from the fact that my updater has issues with properly formatting your `full_description.txt` as it partly uses "icons" as bullet-points, which result in "partially broken Markdown" :see_no_evil: and thus I've told it to ignore the file).

**Comment by DeweyReed** [comment]
I thought your repo was a standalone distributing channel. Which solution makes more sense to you, keep it in README or remove it?

**Comment by IzzySoft** [comment]
> I thought your repo was a standalone distributing channel.

In a way it is. It still requires an F-Droid client for "good use". And if you have that, the F-Droid catalog is already available there. So as my repo runs on personal space, I try to keep the overlap low (especially with non-reproducible builds, as the "signature mismatch" often causes confusion – which is not the case with your app as it builds reproducibly, hence my reaching out).

> Which solution makes more sense to you, keep it in README or remove it?

Depends on what you want. If you want it to stay with my repo (e.g. for faster updates, as my updater usually grabs your APK within 24h while F-Droid's build cycle takes at least 2 days), you just need to say so and all can remain as-is :wink:

**Comment by DeweyReed** [comment]
Thanks for your explanation! :D

I want to remove the app to keep the overlap low. Faster updates are not a problem, as the app updates infrequently. If nothing is missed, I'll create a commit to remove the link.

**Comment by IzzySoft** [comment]
Thanks @DeweyReed – I then marked it to remove. As it entered F-Droid on 2024-04-06, it would be due from now on (after 10..14d, so we're in the middle of that range – no worries if it stays a few days more). To keep confusion on the user's end as low as possible, I'd wait for your "Go" signalling the badge/link was removed, so nobody ends up with a 404 from it.

**Comment by DeweyReed** [comment]
You're so considerate! The link is gone now. :D

**Comment by IzzySoft** [comment]
OK, gone then with the next sync. Should you need it back later for some reason, just let me know.
