### ISSUE TITLE
V7.4.0 still not on F-Droid

### ISSUE THREAD

**Issue by Stephan-P** [timer-machine/timer-machine-android#74]
Two weeks after release, version 7.4.0 is still not abailable at F-Droid.
Is that something you can influence?

**Comment by DeweyReed** [comment]
That's weird. I'll see what I can do.

**Comment by DeweyReed** [comment]
Thank you very much! It was a metadata problem, and [I've fixed it](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14419). I'll comment here when the new release is available in F-Droid.

**Comment by DeweyReed** [comment]
Hi, [the new release](https://f-droid.org/en/packages/io.github.deweyreed.timer.other/) is available in F-droid!
