### ISSUE TITLE
What does the "halt" step do?

### ISSUE THREAD

**Issue by Ytrog** [timer-machine/timer-machine-android#75]
Hi,

I'm trying to figure out what the "halt" step does as it seems to just make the timer go on indefinately. What is its purpose?

**Comment by DeweyReed** [comment]
It's for steps with indeterminate duration. For example, people may want to check how fast or slow they do something. After finishing the activity, they can manually move on to the next step by tapping the down button.

**Comment by Ytrog** [comment]
Ah ok. I would never have figured _that_ out tbh.

Thank you for your prompt answer.
