### ISSUE TITLE
Screen turns off

### ISSUE THREAD

**Issue by spavlovich001** [timer-machine/timer-machine-android#76]
When the workout is long, the screen should not turn off

**Comment by DeweyReed** [comment]
What's your value of "Screen Brightness" in the app settings? To make it the same as the system, change it to "Use system default." If the system setting doesn't turn off the screen after some time, no app can either.

**Comment by landry314** [comment]
i have no idea what your reply ia suppose to mean... apps can keep the screen on while idle.

android:keepScreenOn="true" in XML

i started using your app and the screen goes off during a workout. it is an easy fix.

there are many ways to do it but it can just be on when a workout starts then off at the end.

> What's your value of "Screen Brightness" in the app settings? To make it the same as the system, change it to "Use system default." If the system setting doesn't turn off the screen after some time, no app can either.

**Comment by landry314** [comment]
oh, now i understand! "screen brightness" is a setting FOR this. the name is really not clear.
