### ISSUE TITLE
Unsuitable interface for sports activities

### ISSUE THREAD

**Issue by spavlovich001** [timer-machine/timer-machine-android#78]
There is the best program in this class - impetus. 

http://0x0.st/HnM6.jpg

Currently unsupported. There is a lot done as it should be. For example:

1. large title of the current exercise

2. large buttons

3. long tap of buttons

3. one single button to skip the current exercise

4. changing background color when changing exercise\rest

5. convenient view total_left/total elapsed

6. сonvenient locking of buttons at start

And much more. Please install this program for yourself and see what you can best take from it. A lot has been done there wisely

**Comment by DeweyReed** [comment]
You could increase the text size of the remaining time and add elapsed time chips in the "Customize Screen" entry of the app settings.

There are plans for a new timer-running screen, but it's impossible to copy the whole screen from the app you mentioned because the features the two apps provide aren't identical.

**Comment by spavlovich001** [comment]
> You could increase the text size of the remaining time and add elapsed time chips in the "Customize Screen" entry of the app settings.
> 
> There are plans for a new timer-running screen, but it's impossible to copy the whole screen from the app you mentioned because the features the two apps provide aren't identical.



You could increase the text size of the remaining time and add elapsed time chips in the "Customize Screen" entry of the app settings.

There are plans for a new timer-running screen, but it's impossible to copy the whole screen from the app you mentioned because the features the two apps provide aren't identical.
