### ISSUE TITLE
Suggesting to create shortcuts for homescreen 

### ISSUE THREAD

**Issue by heintunzaww** [timer-machine/timer-machine-android#79]
That will be a better way to use the app.

**Comment by DeweyReed** [comment]
To create a shortcut for a timer, tap the menu(three dots) button on the timer-running screen, and then tap "Create Shortcut."

**Comment by heintunzaww** [comment]
Thanks you for replying me,
I try to find where the shortcut feature was,
I couldn't find it and I ended up emailing you.
Sorry about that.

Thanks you so much for this reply, and by the way, you guys are the ones
that make Android a lot better for me. So, I just want to say Thanks you so
much to you again.

**Comment by DeweyReed** [comment]
Thanks for your support and suggestions! :D
