### ISSUE TITLE
Feature request: Confirmation Step

### ISSUE THREAD

**Issue by zendynar** [timer-machine/timer-machine-android#8]
Hey, thanks a lot for the app and for adding it to IzzyOnDroid F-Droid repo!

I started using it today and have a feature request - a confirmation step. What I mean is that it is a step acts as a pause - until it is manually confirmed. Only then the next timer would start.

This is really useful in scenarios where you need to do something at fixed intervals and track time between. For example, if you need to eat every 4 hours, the next 4-hour timer should start after you've finished your first meal, which can take different. The confirmation step would help that workflow a lot.

**Comment by DeweyReed** [comment]
@zendynar  There is a reminder called "Halt." After adding it to a step, the step would count up from 0s and stay at the step until you manually go to the next step. You could still set the duration of the step, although time will go beyond it.

Let me know if this can help you. :D

**Comment by zendynar** [comment]
@DeweyReed Thanks, it should work. I found it later yesterday too but it wasn't too obvious how it should work. I guess the issue can be closed then.
