### ISSUE TITLE
how to choose to play timer sound globally or in headphones only?

### ISSUE THREAD

**Issue by Daoet** [timer-machine/timer-machine-android#80]
this feature was mentioned in the F-droid description but i couldn't figure out how this is set or done within the app. can you please elaborate on it?

**Comment by DeweyReed** [comment]
Hi! You can play around with different "Sound Type" options in the app settings and see if they work for you. Usually, the "Alarm" option would make the sound play globally.

**Comment by DeweyReed** [comment]
To access the option in the app settings, tap the menu icon in the timer list's top-left corner of the screen and then tap "Settings."
