### ISSUE TITLE
Bug: application crashes when adding music several times in a row

### ISSUE THREAD

**Issue by mathe00** [timer-machine/timer-machine-android#82]
Hello, I would like to report a bug: the application crashes when adding music several times in a row. For example, I add the music "Happy Music" to a step and if I add the same music to another step, it makes me crash the application without saving anything. 

I don't have more time to do more tests, I'm sorry. But in any case, it's not an uncommon occurrence, it's happened to me many times, and I've even had several times the message from the application telling me that it has detected a crash and that it could be due to a process kill by Android, but obviously I've put everything in place so as not to have this kind of problem. It really happens when I add music (I'm not sure if it only happens for the same music).

**Workaround while waiting for a patch:**

Create a single first step with music, then duplicate this step several times and change the label of each duplicated step to make it look as if I'd created each new step with music from scratch.

**Comment by DeweyReed** [comment]
Hi, I'm sorry for the inconvenience. 

The newest release(7.5.0) fixed a related crash. You can try it to see if the crash is gone.

Google Play delayed the update for multiple days, so if the update isn't available in Google Play, you can download the APK at <https://drive.google.com/open?id=1YHIdW77fuxmyQ7sFza1LEIqmhzBygEZx>. If you're using F-Droid, which has yet to release the new version, you can download the release directly at <https://github.com/timer-machine/timer-machine-android/releases/tag/7.5.0>. Notice that either way, you don't need to uninstall the app first.
