### ISSUE TITLE
Design for battery saving?

### ISSUE THREAD

**Issue by yfdyh000** [timer-machine/timer-machine-android#84]
I noticed that the app's battery statistics included long periods of "stay awake" (保持唤醒状态), and I guess it stayed awake to check timers and update status and notifications. So, maybe add a mode that increases the wake interval and reduces the wake-up time, such as setting a system waker to wake up every minute unless something is happening in the near future or the screen / the app is active?

By the way, I've added a timer for an hourly action.

**Comment by DeweyReed** [comment]
The app values more accurate timing, and battery consumption is an inevitable cost.

If the app set an alarm and woke up the device later, what would happen on many devices would be that the alarm never got triggered and failed to remind the user eventually.

Moreover, despite everything the app has done, the system still kills it in the background on some devices.

If you need a long timer, please consider the system countdown timer, which is more reliable and energy-saving.
