### ISSUE TITLE
[Feature Request] Timer Loop count sound 

### ISSUE THREAD

**Issue by mahtoles** [timer-machine/timer-machine-android#86]
Hello, 

I appreciate this is the one of the best application for timer exercise. 

I request you to add the loop count sound when timer is in progress. 

Let's say I am doing one set of exercise for 10 counts but I am not able to know which count I am on or how much count his pending. 

Request you to add this important feature.

**Comment by DeweyReed** [comment]
To let the timer speak the current loop, add the Voice reminder to a step, edit its content, and add variables that end with "Loop" like "TLoop" and "GLoop." You can long-press those variables to check their meanings.

**Comment by mahtoles** [comment]
Thank you... Very much

**Comment by mahtoles** [comment]
Working as expected as per given solution
