### ISSUE TITLE
Setting -  Audio focus type issue.

### ISSUE THREAD

**Issue by mahtoles** [timer-machine/timer-machine-android#89]
Best application for exercise.

I observed when I set setting i.e.lower other sound. App sound while doing exercise repeats half, count and voice to double time.

Please check.

Thank you

**Comment by mahtoles** [comment]
[timer-machine-2024-06-08-11-14.json](https://github.com/user-attachments/files/15746616/timer-machine-2024-06-08-11-14.json)

Here is backup.. you can import and see issue. 
If quick fix then share updated one.

**Comment by DeweyReed** [comment]
Could you elaborate on "repeats half, count and voice to double time?"

**Comment by mahtoles** [comment]
Hello,

I edited json file and it worked fine. Attached for your ref.

Issue: Everything was normal but I thought to do changes in the setting "Lower other sound " and may be some other settings. From then each voice started repeating two times. You can import the Json file given in the earlier message and observed the same issue. And later you just clear the cache and data and restore the given J
[New document 2.json](https://github.com/user-attachments/files/15750642/New.document.2.json)
son file in this message and you will find that issue is not there. 

Thank you

**Comment by DeweyReed** [comment]
Does every step that contains a "Voice" reminder repeat the name of the step twice on your device?

I imported the data but failed to reproduce the problem.

- What Text-to-speech engine do you use in the system settings?
- Does changing to another engine, like Google's TTS, solve the problem?
- Can you reproduce the problem when a step only contains a "Voice" reminder?
- Does the problem persist if you change the "Audio Focus Type" value to "None?"

**Comment by mahtoles** [comment]
What Text-to-speech engine do you use in the system settings? TTSLee
Does changing to another engine, like Google's TTS, solve the problem? Not tested
Can you reproduce the problem when a step only contains a "Voice" reminder? Step and half and count also double voice 
Does the problem persist if you change the "Audio Focus Type" value to "None?" None has noissue


If you are unable to close produce the issue again then kindly ignore for this time because I have modified the json file and re imported and now issue is resolved for this time

**Comment by DeweyReed** [comment]
Does the problem persist? Because I can't reproduce the problem, I can do nothing now.

If the speech produced by TTS is repeated twice, I suspect it could be a problem with the TTS engine.

**Comment by mahtoles** [comment]
Yes could be tts issue. I will raise issue same issue again if repeat.  Will give more details

**Comment by mahtoles** [comment]
Closed as issue not repeated

**Comment by mahtoles** [comment]
Yes could be tts issue. I will raise issue same issue again if repeat. Will give more details
