### ISSUE TITLE
[Feature request] - Beep at end

### ISSUE THREAD

**Issue by extendednotes** [timer-machine/timer-machine-android#9]
What a great app, thank you so much! I would like to use the app for sports activities. Therefore, it would be great if you could set the beep option (x-times) not only at the beginning of an element, but also at the end, for example to count the last 5 seconds. 
And it would be great if you can choose your own custom beep sound, I do not like the "phonish" DTMF tones :)

**Comment by DeweyReed** [comment]
Instead of Beep, you could use Count, which will count the last several seconds as you described. It has some performance issues under certain circumstances. I've been dealing with it.

You could create a custom beep count file and use it with Music.

**Comment by extendednotes** [comment]
I'm using the F-Droid version and do not have google play services installed. Therefore I get only an "text to speech error" and can't use the count function, but thanks anyway.

**Comment by DeweyReed** [comment]
@extendednotes  TextToSpeech doesn't require google play services. The engine for it is just another app on the phone.
Here is a simple guideline: <https://github.com/timer-machine/Grocery/blob/master/en/configure-tts.md>
