### ISSUE TITLE
Feature Request: Ability to Save Incomplete Timer Sessions

### ISSUE THREAD

**Issue by wbsnpc** [timer-machine/timer-machine-android#98]
Sometimes, when I'm unable to finish a repeating timer (or one of its groups), I need to interrupt the session, but the progress isn't saved. I would like to save this incomplete record

**Comment by mahtoles** [comment]
This issue reported earlier. Please see replies in this post.

https://github.com/timer-machine/timer-machine-android/issues/91

**Comment by DeweyReed** [comment]
Since many people request this feature, it will be a new feature. The discussion will be merged into the existing issue.
